files:
  - source: /locales/en/translation.json
    translation: /locales/%locale%/translation.json
    languages_mapping:
      locale:
        cs: cs
        de: de
        es-ES: es_es
        fr: fr
        gd: gd
        hu: hu
        id: id
        it: it
        ja: ja
        ko: ko
        'no': 'no'
        pt-PT: pt_pt
        zh-CN: zh_cn
        zh-TW: zh_tw
