files:
  - source: /locales/en/translation.json
    translation: /locales/%locale%/translation.json
    languages_mapping:
      locale:
        cs: cs
        de: de
        es-ES: es_es
        eu: eu
        fa: fa
        fr: fr
        gd: gd
        hu: hu
        id: id
        is: is
        it: it
        ja: ja
        ko: ko
        'no': 'no'
        pl: pl
        pt-PT: pt_pt
        ru: ru
        si-LK: si
        sv-SE: sv_se
        tzm: tzm
        zh-CN: zh_cn
        zh-TW: zh_tw
